### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by seanyen** [cartographer-project/cartographer_ros#1327] opened 2019-06-18 18:53 UTC
It's been a year since the `v1.0` release and there are so many commits in the past year. Any plan to make another release?

**Comment by xperroni** [comment] 2019-06-26 21:04
I second that, if only to make the latest version up-to-date with the documentation — some features mentioned in the [ROS API reference](https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html) (for example, the `get_trajectory_states` service) are not implemented in the 1.0.0 release.

**Comment by MichaelGrupp** [comment] 2020-10-14 17:40
Duplicate of #1512

**Closed by MichaelGrupp** 2020-10-14 17:40 UTC
