### ISSUE TITLE
catkin_make error in cartographer_ros

### ISSUE THREAD

**Issue by Babaevzhu** [cartographer-project/cartographer_ros#1117] opened 2018-12-05 04:06 UTC
Hi, I install cartographer_ros following the documents:https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html 
when I run **catkin_make_isolated --install --use-ninja**, I got the error as follow:

Finished processing package [4 of 5]: 'cartographer_ros'

==> Processing catkin package: 'cartographer_rviz'
==> Building with env: '/home/qw/goo_ws/install_isolated/env.sh'
==> cmake /home/qw/goo_ws/src/cartographer_ros/cartographer_rviz -DCATKIN_DEVEL_PREFIX=/home/qw/goo_ws/devel_isolated/cartographer_rviz -DCMAKE_INSTALL_PREFIX=/home/qw/goo_ws/install_isolated -G Ninja in '/home/qw/goo_ws/build_isolated/cartographer_rviz'
-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.12.0 installed in: /home/qw/goo_ws/install_isolated with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, SchurSpecializations, OpenMP]
-- Build type: Release
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   iostreams
--   regex
-- Using CATKIN_DEVEL_PREFIX: /home/qw/goo_ws/devel_isolated/cartographer_rviz
-- Using CMAKE_PREFIX_PATH: /home/qw/goo_ws/install_isolated;/opt/ros/indigo
-- This workspace overlays: /home/qw/goo_ws/install_isolated;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/qw/goo_ws/build_isolated/cartographer_rviz/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
**CMake Error at /home/qw/goo_ws/install_isolated/share/cartographer_ros/cmake/cartographer_rosConfig.cmake:141 (message):
  Project 'cartographer_rviz' tried to find library '-lpthread'.  The library
  is neither a target nor built/installed properly.  Did you compile project
  'cartographer_ros'? Did you find_package() it before the subdirectory
  containing its code is included?
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:36 (find_package)**

-- Configuring incomplete, errors occurred!
See also "/home/qw/goo_ws/build_isolated/cartographer_rviz/CMakeFiles/CMakeOutput.log".
See also "/home/qw/goo_ws/build_isolated/cartographer_rviz/CMakeFiles/CMakeError.log".
<== Failed to process package 'cartographer_rviz': 
  Command '['/home/qw/goo_ws/install_isolated/env.sh', 'cmake', '/home/qw/goo_ws/src/cartographer_ros/cartographer_rviz', '-DCATKIN_DEVEL_PREFIX=/home/qw/goo_ws/devel_isolated/cartographer_rviz', '-DCMAKE_INSTALL_PREFIX=/home/qw/goo_ws/install_isolated', '-G', 'Ninja']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/qw/goo_ws/build_isolated/cartographer_rviz && /home/qw/goo_ws/install_isolated/env.sh cmake /home/qw/goo_ws/src/cartographer_ros/cartographer_rviz -DCATKIN_DEVEL_PREFIX=/home/qw/goo_ws/devel_isolated/cartographer_rviz -DCMAKE_INSTALL_PREFIX=/home/qw/goo_ws/install_isolated -G Ninja

Command failed, exiting.

can anyone help me? thx u very much

**Comment by TouchDeeper** [comment] 2018-12-25 05:55
Hi,@Babaevzhu
Have you solved the problem? I also encountered this problem. Can you give me some advice?

**Comment by xiaoDongSky** [comment] 2019-04-12 06:42
@Babaevzhu  I also encountered this problem in ubuntu 16.04，Can you give me some advice?

**Comment by MichaelGrupp** [comment] 2020-10-23 12:22
This looks like a duplicate of https://github.com/cartographer-project/cartographer_ros/issues/1163, please check if the discussion there helps you too.

**Closed by MichaelGrupp** 2020-10-23 12:22 UTC
