### ISSUE TITLE
Example map skewed(b3-2016-04-05-14-14-00.bag)

### ISSUE THREAD

**Issue by eithwa** [cartographer-project/cartographer_ros#1432] opened 2019-12-23 16:42 UTC
I try to run the sample program [here](https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html#first-person-visualization-of-point-clouds)
but my result graph is slightly skewed
I used two computers (indigo and kinetic) to get similar results
![img](https://i.imgur.com/n8ZFdXT.png)
I get good results with older version
![good](https://i.imgur.com/Ck2fV8E.png)
how can I get good mapping in the latest version
do I need to change any parameter in the lua file?

**Comment by MichaelGrupp** [comment] 2020-10-14 17:13
This is a duplicate of: https://github.com/cartographer-project/cartographer_ros/issues/1357, see my answer there. Closing this here.

**Closed by MichaelGrupp** 2020-10-14 17:13 UTC
