### ISSUE TITLE
assets writer map output (pmg) doesnt match submaps and doenst show all obstacles

### ISSUE THREAD

**Issue by Leisa2019** [cartographer-project/cartographer_ros#1376] opened 2019-08-12 15:41 UTC
Hey there, 
I've been having an issue with converting my cartographer pbstream-output to a usable pgm-file using the asset writer. The results of the submaps shown in RViz show all the obsticals that I need. After saving the map as .gpm, I only seem to get parts of that result. What I already tried is changing the miss/hit probabilities in the .lua-file, which only made it worst. I also tried setting insert_free_space to false, which resulted in a better obstical recognition but in a gray and black map, that includes basically everything that the sensors ever recorded and that is overlapped. 
I get that the asset writer is there for the recombination of the submaps including propabilities or color filters, but what I don't get is that I can't tune it in a way that I can receive a gpm that resembles the RVIZ-View.
 Why does the hit-probability have to be >0.5 and the miss probability <0.5? 
Does anyone else have this issue and maybe a solution or a tip?

**Comment by Leisa2019** [comment] 2019-08-13 06:35
![95EC0EFF-755C-4ABB-A622-C03E97889364](https://user-images.githubusercontent.com/54025541/62920158-2d5f8900-bda5-11e9-92d8-1d78aa1e9fac.jpeg)
![E38D78AD-9E27-4496-B845-47BC955D67F7](https://user-images.githubusercontent.com/54025541/62920159-2df81f80-bda5-11e9-9ccb-17090f763a73.jpeg)
Here are some pictures showing the issue.

**Comment by facontidavide** [comment] 2019-10-10 13:33
This is a very well known problem (duplicate of #963

I am sending a PR to fix it.

**Comment by gameinskysky** [comment] 2020-01-15 07:15
Thanks for your help

**Closed** 2020-06-09 10:36 UTC
